# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20191028_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
