# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-26 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN PROGRESS', 'In progress'), ('IN REVIEW', 'In review'), ('COMPLETE', 'Complete')], default='CREATED', max_length=20)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_started', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('donations', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('views', models.IntegerField(default=0)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
