# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0002_auto_20191029_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='bug',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
